const headlines: string[] = [
    "Inspiration Starts Here.",
    "Uplift Your Day.",
    "A Positive Mindset Begins Now.",
    "Find Your Daily Spark.",
    "Your Motivation Awaits.",
    "Nourish Your Spirit.",
    "Fuel Your Inner Strength.",
    "Today's Dose of Positivity.",
    "Choose Hope.",
    "Words to Elevate Your Day.",
    "Pause. Reflect. Inspire.",
    "What Does Your Soul Need?",
    "Insights for Your Journey.",
    "Thoughts to Guide Your Path.",
    "A Nugget of Wisdom for You.",
    "Mindfulness Starts Here.",
    "Seeds of Growth.",
    "A Moment for Inner Discovery.",
    "Where Will Your Thoughts Take You?",
    "Reflect for Resilience.",
    "Embrace Calmness.",
    "Stoke Your Inner Fire.",
    "Cultivate Courage.",
    "Discover Your Inner Peace.",
    "Your Daily Boost of Joy.",
    "Find Your Strength Today.",
    "A Dose of Optimism.",
    "Choose Resilience.",
    "Nurture Your Happiness.",
    "Awaken Your Inner Light.",
    "Inspiration...Delivered!",
    "Today's Cosmic Message.",
    "Your Personal Fortune Cookie.",
    "Words to Unfold Your Day.",
    "What Will You Discover Today?",
    "A Little Magic for Your Soul.",
    "The Universe Has a Whisper for You.",
    "Inspiration Hotline: Dial in Now!",
    "Unlock Your Day's Potential.",
    "Where Will Your Inspiration Lead?",
    "Seize the Day!",
    "Make Today Extraordinary.",
    "Inspiration for Bold Action.",
    "You've Got This.",
    "Believe. Achieve. Conquer.",
    "Dare to Dream, Dare to Do.",
    "Turn Inspiration into Action.",
    "Manifest Your Best Day.",
    "Step Into Your Power.",
    "Be the Change You Wish to See.",
    "Fill Your Cup of Inspiration.",
    "Plant Seeds of Positivity.",
    "Let Your Light Shine.",
    "Unwind Your Thoughts.",
    "Ignite Your Passion.",
    "Weather Any Storm.",
    "Navigate with Your Inner Compass.",
    "Build Your Bridge to Possibility.",
    "Open the Door to Inspiration.",
    "Find Your Silver Lining.",
    "Inspire.",
    "Believe.",
    "Hope.",
    "Grow.",
    "Shine.",
    "Thrive.",
    "Motivate.",
    "Dream.",
    "Uplift.",
    "Breathe."
];


export const getRandomHeadline = (): string => {
    const index = Math.floor(Math.random() * headlines.length);
    return headlines[index];
}